### ISSUE TITLE
login.js doesn't work with trailing slash in the url

### ISSUE THREAD

**Issue by narenranjit** [forio/epicenter-js-libs#101]
regex at `getAccountProjectFromUrl` fails for https://forio.com/app/acme-simulations-0/hello_world_python/

Rather than fix here, replace by using urlservice to be consistent

**Comment by narenranjit** [comment]
Actually it always passes in `undefined` but the auth service pulls it from the url itself. So guessing from url by  login.js is actually redundant

**Comment by mmrj** [comment]
https://issues.forio.com/browse/EPICENTER-1462
