### ISSUE TITLE
auth manager: should require either groupName or groupId for login

### ISSUE THREAD

**Issue by mmrj** [forio/epicenter-js-libs#102]
In 1.5, the following returns a session object that includes both the 'groupId' and the 'groupName' that goes with it:

```
	var auth = new F.manager.AuthManager();

	auth.login({
	       account: 'acme-simulations-0',
	       userName: 'user2',
	       password: 'xxx',
	       project: 'hello_world_python',
	       groupId: 'b0315d47-fb61-46bc-ad14-5e418638bd12',
	   }).then(function () {	
			var session = auth.getCurrentUserSessionInfo();
			console.log("session = ", session);	
	});
```
(This is an end user that is in multiple groups.)

However, if I pass in the `groupName` instead of the `groupId`, I get errors (400 during DELETE to /authentication/token, and never get to the log statement). It would be nice if I could choose which to pass in, and have the Manager figure it out for me and give me a session with both.

**Comment by narenranjit** [comment]
The API requires `groupId` and doesn't take `groupName`, so I think the right place to fix this is at the API level (otherwise this means an additional round trip to the server to translate name-to-id). Closing this here for now.
