### ISSUE TITLE
auth manager: login() with project but not groupId --> should give error message

### ISSUE THREAD

**Issue by mmrj** [forio/epicenter-js-libs#104]
In 1.5, for the Auth Manager login() call when you are logging in an end user: if the `project` is specified then the `groupId` is required; otherwise the `project` is optional.

It would be great if, if you include the `project` but not the `groupId`, there was some indication of what you've done wrong. Currently you just get a 400 on DELETE /authentication/{token}.

**Comment by mmrj** [comment]
closing - updating in docs. the error message is there you just don't see it until you look at the authAdapter that's the argument of the promise, e.g.

```
authMgr.login().fail(function(authAdapter) { console.log(authAdapter.statusText); }); 
```

**Comment by jaimedp** [comment]
Actually for the fail() callback you do not get an authAdapter, you get an xhr object. the xhr is the actual ajax request that failed

**Comment by mmrj** [comment]
talked w/ @jaimedp -- you don't really get either. you get a custom status object.
![screen shot 2015-06-23 at 9 51 25 am](https://cloud.githubusercontent.com/assets/1653043/8312466/82976ad0-1991-11e5-922b-8bb42b290c9d.png)

clarified in docs in branch "epicenter-926-testing-1.5", pr forthcoming
