### ISSUE TITLE
Change default login.html to be centerd

### ISSUE THREAD

**Issue by narenranjit** [forio/epicenter-js-libs#114]
<img width="845" alt="screen shot 2015-07-06 at 2 20 24 pm" src="https://cloud.githubusercontent.com/assets/830274/8533469/2c989240-23ea-11e5-97c4-b0ed2113a768.png">

Form is bunched on the top right now, change this to be centered through login.css

**Comment by narenranjit** [comment]
fixed by andy

**Comment by mmrj** [comment]
verified
