### ISSUE TITLE
clarify relationship between user channel and worlds

### ISSUE THREAD

**Issue by mmrj** [forio/epicenter-js-libs#118]
according to Will, the world should now not be included during the user channel -- e.g. /user/{account id}/{project id}/{group name}/{user id}, NOT /user/{account id}/{project id}/{group name}/{world id]/{user id}

however, the Epicenter Channel Manager .getUserChannel() requires the world object as a parameter (in epicenter.js 1.5.0). 

is this still necessary? I feel like we missed some communication between projects on this, just wanted to make sure we're all on the same page -- logging this issue as a placeholder to check in.

**Comment by narenranjit** [comment]
is there a ticket on this that I missed? Also i have the endpoint as "users/", but the doc say "user/" - did that change or never work?

**Comment by mmrj** [comment]
re user vs users, docs were wrong, updated in EPICENTER-1057

re ticket for when this changed is I think EPICENTER-79 (I thought we had a more specific one, but I'm not finding it ...)

sorry to not get back on this -- it was on my list for a couple of weeks to check in on during sim-dev meeting, but when we kept not getting to it seems to have magically fallen off my list : (

**Comment by mmrj** [comment]
https://issues.forio.com/browse/EPICENTER-1469
