### ISSUE TITLE
asset api adapter: not passing authorization header 

### ISSUE THREAD

**Issue by mmrj** [forio/epicenter-js-libs#122]
this bug is based on epicenter-edge.js built from #120 
using:
```
    aa = new F.service.Asset({
        account: 'acme-simulations-0',
        project: 'epi-1094-team-auth',
        group: group,
        userId: userid,
        transport: {
            contentType: 'application/json'
        }
    });

    aa.create(epiFileName, {
        encoding: 'BASE_64',
        data: 'VGhpcyBpcyBhIHRlc3QgZmlsZS4=',
        contentType: 'text/plain'
    }, { scope: 'user' });
```

the POST to https://api.forio.com/asset/user/acme-simulations-0/epi-1094-team-auth/group-1/37383850-4ef4-45f4-bec8-30c0ca060e36/epiTest.txt returns 401 unauthorized.

it looks like the problem is that the request being sent does not include an Authorization header. trying the POST in Postman with the Authorization header successfully creates the file.

**Comment by rvillarreal** [comment]
Molly you would have to add the token manually to the Asset service:

```
aa = new F.service.Asset({
        token: '{{TOKEN_ID}}'
        account: 'acme-simulations-0',
        project: 'epi-1094-team-auth',
        group: group,
        userId: userid,
        transport: {
            contentType: 'application/json'
        }
    });

    aa.create(epiFileName, {
        encoding: 'BASE_64',
        data: 'VGhpcyBpcyBhIHRlc3QgZmlsZS4=',
        contentType: 'text/plain'
    }, { scope: 'user' });
```
should work.

**Comment by rvillarreal** [comment]
As a side note, the token is automatically added if there is a login session via the AuthManager

**Comment by narenranjit** [comment]
If the token is automatically added if you're logged in, I'm fine resolving this. @mmrj re-open if this doesn't match what you're seeing.

**Comment by mmrj** [comment]
verified this works if you pass in the token to the `new F.service.Asset()` call per Ricardo's sample above.

verified this works if you are logged in:
```
    var authMgr = new F.manager.AuthManager({
      account: 'acme-simulations-0',
      userName: 'fac1',
      password: // password here
      groupId: '47bb3018-6e37-4a43-be55-4b894a374e41'
    });

    authMgr.login().then( function() {
        aa = new F.service.Asset({
            account: 'acme-simulations-0',
            project: 'epi-1094-team-auth',
            group: group,
            userId: userid,
            transport: { contentType: 'application/json' }
        });
    });
```

@rvillarreal note that `new F.service.Asset()` does error if I don't include account, project, or group ... which is a little odd since it just got those when I logged in. do you think it should default them to the values that I used when I logged in? I could see arguments either way.
