### ISSUE TITLE
need to expose account, project in default configuration options for state & member api adapters

### ISSUE THREAD

**Issue by mmrj** [forio/epicenter-js-libs#140]
the following services (aka api adapters) for epicenter.js list account and project as configuration options both in the code and in the docs:
 - asset
 - world
 - run
 - data

the following don't but we think it's ok:
 - variables
 - auth service (exposes account only)

the following don't, but should:
 - state
 - member

the use case for exposing account, project explicitly is when you're developing locally and they can't be pulled from the uri.

for additional context for this request, see https://issues.forio.com/browse/EPICENTER-1251

**Comment by narenranjit** [comment]
The state adapter isn't by account/project though -- it's only by runid. I think the member api is the same. Reopen if I'm missing something.

**Comment by mmrj** [comment]
sounds good -- just wanted to confirm (this came up in our meeting earlier today).
