### ISSUE TITLE
grunt tests can't pass with newly implemented functionality

### ISSUE THREAD

**Issue by jaimedp** [forio/epicenter-js-libs#17]
grunt tests are including epicenter.min.js but that file does not get cerated until the tests pass, so doing it TDD/BDD style is not possible, you have to implement the functionality first, call grunt production, then implement tests on the functionality, also iterating on the code to fix a test is hard

**Comment by mmrj** [comment]
verified that grunt tests use epicenter-edge now, and `grunt test` build/rebuilds epicenter-edge.
