### ISSUE TITLE
World api adapter: Add user - be more forgiving of user-id formats

### ISSUE THREAD

**Issue by narenranjit** [forio/epicenter-js-libs#46]
The following should all work

```javacript
.addUser('<userid')
.addUser(['<userid1>', '<userid2>'])

.addUser({userid: 1})
.addUser([{userid: 1}, {userid: 2}])

```

**Comment by mmrj** [comment]
however, this is complicated by the fact that addUser should be able to take an object with more fields than just userId.
```
gm.addUsers({userId: 'b1c19dda-2d2e-4777-ad5d-3929f17e86d3', role: 'VP Marketing'});
```
should (and does) work.

**Comment by jaimedp** [comment]
what do you mean by supporing:

`.addUser(' .addUser(['', ''])`

Why would you do that?

**Comment by narenranjit** [comment]
I left out the code-comment blocks, so github interpreted them some weird way :) Take a look now

**Comment by mmrj** [comment]
verified
