### ISSUE TITLE
World api adapter: Add user - pass in 'world' as the second parameter

### ISSUE THREAD

**Issue by narenranjit** [forio/epicenter-js-libs#47]
Right now the  signature for 'addUser' is  `.addUser(userid, worldid )` 

so only way to add an user to a world is `.addUser(userid, {filter: worldid})`

Change signature to  `.addUser(userid, worldid, options )` instead

**Comment by jaimedp** [comment]
The idea is that if you load a world (or create one) then you can user `AddUsers(...)` without the filter (as the filter is automatically populated.

but I guess chaining the signature and allowing the second parameter to be the options if its an object an  no third param is given would allow us to support both formats

**Comment by mmrj** [comment]
reopening with questions -- passing the world id as the second option works, but I can't tell from the PR how I should pass the filter now. 

here's the code I'm using: 

```
(function() {

console.log("testing pull/47");

var wa = new F.service.World({
    account: 'acme-simulations-0',
    project: 'hello_world_python',
    group: 'js-libs-team2',
    server: { host: 'api.forio.com' }
});
wa.create({model: 'hello_world.py'})
    .then(function(world){
        wa.addUsers('b1c19dda-2d2e-4777-ad5d-3929f17e86d3', world.id);
        wa.addUsers('bc0d74d6-c4e7-41e9-860b-a11a0a190939', {filter: world.id});
    });


})();
```
only adds user b1c1 to the world.
the addUsers with bc0d is a successful POST but the response is just `[]`. how should we be making the second call?

**Comment by mmrj** [comment]
https://issues.forio.com/browse/EPICENTER-1452
