### ISSUE TITLE
auth manager: if user is in multiple groups, still able to log in, can't tell which group

### ISSUE THREAD

**Issue by mmrj** [forio/epicenter-js-libs#60]
user1 is an end user in three groups. 

```
authMgr.login({ 
           account: 'acme-simulations-0', 
           userName: 'user1',
           password: 'passw0rd'
    	})
    	.then(function(authAdapter) { 
    		console.log("user access token is: ", authAdapter.auth.access_token); 
    		console.log("user info is: ", authAdapter);
    	});
```

the login seems to work -- authAdapter.auth.access_token is an access token
but authAdapater.userGroups is an array of all the groups that user1 is part of (there are 3). 

how do I tell which group the user is logged in to?

**Comment by narenranjit** [comment]
I could be wrong on this, @rvillarreal can answer more definitively, but I think that's okay.

You haven't logged in  yet - if a user does this on a login page, he'll get a list of different groups he's a part of in a dialog to pick. He'd then need to select one, and call .login again, but passing in the group this time. I think this is what `components/login` does too. (haven't checked)

**Comment by narenranjit** [comment]
On second thoughts I'm not sure if this should've worked on `.then` or on `.fail`. @jaimedp ?

**Comment by jaimedp** [comment]
if the user is in multiple groups that should have `.fail()`ed with the list of groups

**Comment by narenranjit** [comment]
Assigning to ricardo as a bug

**Comment by mmrj** [comment]
talked to @rvillarreal, this is by design in case you want to have end users in your team that are both in multiple projects and multiple groups, you can still log in (and be presented with some kind of "choose your project" page). 

so for authMgr.login for end users: 
 - you can include account, username, password: to log in to the team
 - you can also include project and group: to log in to a specific group
 - if you include project, you have to include group

i think this can be closed.

**Comment by mmrj** [comment]
closing per above comment, will not be migrating this to Epicenter jira.
