### ISSUE TITLE
login component: if login attempt returns an error, we should re-enable the "Login" button

### ISSUE THREAD

**Issue by mmrj** [forio/epicenter-js-libs#68]
so that users can try again. currently you have to reload the page. 

newly loaded page with login component:
![newly loaded page with login component](https://cloud.githubusercontent.com/assets/1653043/6470338/f5e290c0-c197-11e4-80af-ef1ad0a9462b.png)

after error - note login button not enabled:
![after error - note login button not enabled](https://cloud.githubusercontent.com/assets/1653043/6470337/f5d2b358-c197-11e4-9986-ac024ca4f349.png)

**Comment by narenranjit** [comment]
@jaimedp  this is fixed now right?

**Comment by jaimedp** [comment]
Yes, fixed by e828bb50ef120aecf5475cfebb043ce6232186e7

**Comment by mmrj** [comment]
verified in 1.5
