### ISSUE TITLE
World Manager should pull account/ project from url if available

### ISSUE THREAD

**Issue by narenranjit** [forio/epicenter-js-libs#77]
```
var worldManager = new F.manager.WorldManager({run: {account: "team-naren", project: "multiplayer-test", model: "uva.py"}});
```

works but
```
var worldManager = new F.manager.WorldManager({run: {model: "uva.py"}});
```

doesn't when I run it from https://forio.com/app/team-naren/multiplayer-test/.

The `url-config-service` should handle this. Not sure if the world-manager/world-api/run-service aren't handling that correctly.

As an aside the url-config-service could use some rethinking, but will take that to a different issue

**Comment by mmrj** [comment]
verified in 1.5. after logging in (`auth.login()`) as an end user in a multiplayer game to a .html file located on forio.com/app/acme-simulations-0/hello_world_python, both
```
var wMgr = new F.manager.WorldManager({
				account: 'acme-simulations-0',
				project: 'hello_world_python',
				group: 'js-libs-team2',
				model: 'hello_world.py'
		});
```
and
```
var wMgr = new F.manager.WorldManager({ model: 'hello_world.py' });
```

return a world manager from which i can get the current world and current run.

additionally, the second version (including only the model) does NOT work if running my .html file from local.forio.com.
