### ISSUE TITLE
login (and assignment) components should pull in epicenter from cdn

### ISSUE THREAD

**Issue by narenranjit** [forio/epicenter-js-libs#78]
1. The html file under `src` should have `https://forio.com/tools/js-libs/<%= version %>/epicenter.min.js`
2. Create a new task called "grunt:components" which copies the components to /dist and templatizes the html files with package.json (the browserify task does something similar for the json files)

If we do this then people copy-pasting the source won't get messed up.

**Comment by jaimedp** [comment]
This is the assignment branch now, for both components

**Comment by mmrj** [comment]
verified by code inspection of src/components and dist/components, and also because i've pulled different release versions and the dist/components have different versions in them.
